apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: urotaxi-ingress
spec:
  rules:
  - host: urotaxi.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: urotaxi-clusterip-service
            port: 
              number: 8080
