apiVersion: v1
kind: Service
metadata:
  name: urotaxi-mysql-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: urotaxi-mysql
    version: "8.0.32"
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
