apiVersion: v1
kind: PersistentVolume
metadata:
  name: urotaxi-mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: /u01/data
